$schema: https://json-schema.org/draft/2020-12/schema
title: prometheus exporter configuration
type: object
properties:
    add_metric_suffixes:
        description: |-
            AddMetricSuffixes controls whether suffixes are added to metric names. Defaults to true.

            Deprecated: Use TranslationStrategy instead. This setting is ignored when TranslationStrategy is explicitly set.
        type: boolean
    auth:
        description: Auth for this receiver
        type: object
        properties:
            authenticator:
                description: AuthenticatorID specifies the name of the extension to use in order to authenticate the incoming data point.
                type: string
            request_params:
                description: |-
                    RequestParameters is a list of parameters that should be extracted from the request and added to the context.
                    When a parameter is found in both the query string and the header, the value from the query string will be used.
                type: array
                items:
                    type: string
        additionalProperties: false
    compression_algorithms:
        description: 'CompressionAlgorithms configures the list of compression algorithms the server can accept. Default: ["", "gzip", "zstd", "zlib", "snappy", "deflate"]'
        type: array
        items:
            type: string
    const_labels:
        description: ConstLabels are values that are applied for every exported metric.
        type: object
    cors:
        description: CORS configures the server for HTTP cross-origin resource sharing (CORS).
        type: object
        properties:
            allowed_headers:
                description: |-
                    AllowedHeaders sets what headers will be allowed in CORS requests.
                    The Accept, Accept-Language, Content-Type, and Content-Language
                    headers are implicitly allowed. If no headers are listed,
                    X-Requested-With will also be accepted by default. Include "*" to
                    allow any request header.
                type: array
                items:
                    type: string
            allowed_origins:
                description: |-
                    AllowedOrigins sets the allowed values of the Origin header for
                    HTTP/JSON requests to an OTLP receiver. An origin may contain a
                    wildcard (*) to replace 0 or more characters (e.g.,
                    "http://*.domain.com", or "*" to allow any origin).
                type: array
                items:
                    type: string
            max_age:
                description: |-
                    MaxAge sets the value of the Access-Control-Max-Age response header.
                    Set it to the number of seconds that browsers should cache a CORS
                    preflight response for.
                type: integer
        additionalProperties: false
    dialer:
        description: DialerConfig contains options for connecting to an address.
        type: object
        properties:
            timeout:
                description: |-
                    Timeout is the maximum amount of time a dial will wait for
                    a connect to complete. The default is no timeout.
                type: string
                pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
        additionalProperties: false
    enable_open_metrics:
        description: EnableOpenMetrics enables the use of the OpenMetrics encoding option for the prometheus exporter.
        type: boolean
    endpoint:
        description: |-
            Endpoint configures the address for this network connection.
            For TCP and UDP networks, the address has the form "host:port". The host must be a literal IP address,
            or a host name that can be resolved to IP addresses. The port must be a literal port number or a service name.
            If the host is a literal IPv6 address it must be enclosed in square brackets, as in "[2001:db8::1]:80" or
            "[fe80::1%zone]:80". The zone specifies the scope of the literal IPv6 address as defined in RFC 4007.
        type: string
    idle_timeout:
        description: |-
            IdleTimeout is the maximum amount of time to wait for the
            next request when keep-alives are enabled. If IdleTimeout
            is zero, the value of ReadTimeout is used. If both are
            zero, there is no timeout.
        type: string
        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
    include_metadata:
        description: IncludeMetadata propagates the client metadata from the incoming requests to the downstream consumers
        type: boolean
    keep_alives_enabled:
        description: |-
            KeepAlivesEnabled controls whether HTTP keep-alives are enabled.
            By default, keep-alives are always enabled. Only very resource-constrained environments should disable them.
        type: boolean
    max_request_body_size:
        description: 'MaxRequestBodySize sets the maximum request body size in bytes. Default: 20MiB.'
        type: integer
    metric_expiration:
        description: MetricExpiration defines how long metrics are kept without updates
        type: string
        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
    middlewares:
        description: |-
            Middlewares are used to add custom functionality to the HTTP server.
            Middleware handlers are called in the order they appear in this list,
            with the first middleware becoming the outermost handler.
        type: array
        items:
            type: object
            properties:
                id:
                    description: ID specifies the name of the extension to use.
                    type: string
            additionalProperties: false
    namespace:
        description: Namespace if set, exports metrics under the provided value.
        type: string
    read_header_timeout:
        description: |-
            ReadHeaderTimeout is the amount of time allowed to read
            request headers. The connection's read deadline is reset
            after reading the headers and the Handler can decide what
            is considered too slow for the body. If ReadHeaderTimeout
            is zero, the value of ReadTimeout is used. If both are
            zero, there is no timeout.
        type: string
        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
    read_timeout:
        description: |-
            ReadTimeout is the maximum duration for reading the entire
            request, including the body. A zero or negative value means
            there will be no timeout.

            Because ReadTimeout does not let Handlers make per-request
            decisions on each request body's acceptable deadline or
            upload rate, most users will prefer to use
            ReadHeaderTimeout. It is valid to use them both.
        type: string
        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
    resource_to_telemetry_conversion:
        description: ResourceToTelemetrySettings defines configuration for converting resource attributes to metric labels.
        type: object
        properties:
            enabled:
                description: Enabled indicates whether to convert resource attributes to telemetry attributes. Default is `false`.
                type: boolean
            exclude_service_attributes:
                description: |-
                    ExcludeServiceAttributes indicates whether to exclude `service.name`, `service.instance.id` and `service.namespace`
                    resource attributes from being converted to metric attributes. Default is `false`.
                    When set to `true`, these attributes will not be added to metric labels since they are
                    already mapped to Prometheus `job` and `instance` labels respectively.
                type: boolean
        additionalProperties: false
    response_headers:
        description: |-
            Additional headers attached to each HTTP response sent to the client.
            Header values are opaque since they may be sensitive.
        type: object
    send_timestamps:
        description: SendTimestamps will send the underlying scrape timestamp with the export
        type: boolean
    sending_queue:
        description: QueueBatchConfig defines the queue configuration.
        type: object
        properties:
            batch:
                description: BatchConfig it configures how the requests are consumed from the queue and batch together during consumption.
                type: object
                properties:
                    flush_timeout:
                        description: FlushTimeout sets the time after which a batch will be sent regardless of its size.
                        type: string
                        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
                    max_size:
                        description: MaxSize defines the configuration for the maximum size of a batch.
                        type: integer
                    min_size:
                        description: MinSize defines the configuration for the minimum size of a batch.
                        type: integer
                    partition:
                        description: Partition defines the partitioning of the batches configuration.
                        type: object
                        properties:
                            metadata_keys:
                                description: |-
                                    MetadataKeys is a list of client.Metadata keys that will be used to partition
                                    the data into batches. If this setting is empty, a single batcher instance
                                    will be used. When this setting is not empty, one batcher will be used per
                                    distinct combination of values for the listed metadata keys.

                                    Empty value and unset metadata are treated as distinct cases.

                                    Entries are case-insensitive. Duplicated entries will trigger a validation error.
                                type: array
                                items:
                                    type: string
                        additionalProperties: false
                    sizer:
                        description: |-
                            Sizer determines the type of size measurement used by the batch.
                            If not configured, use the same configuration as the queue.
                            It accepts "requests", "items", or "bytes".
                        type: object
                additionalProperties: false
            block_on_overflow:
                description: |-
                    BlockOnOverflow determines the behavior when the component's TotalSize limit is reached.
                    If true, the component will wait for space; otherwise, operations will immediately return a retryable error.
                type: boolean
            num_consumers:
                description: |-
                    NumConsumers is the maximum number of concurrent consumers from the queue.
                    This applies across all different optional configurations from above (e.g. wait_for_result, block_on_overflow, storage, etc.).
                type: integer
            queue_size:
                description: QueueSize represents the maximum data size allowed for concurrent storage and processing.
                type: integer
            sizer:
                description: |-
                    Sizer determines the type of size measurement used by this component.
                    It accepts "requests", "items", or "bytes".
                type: object
            storage:
                description: |-
                    StorageID if not empty, enables the persistent storage and uses the component specified
                    as a storage extension for the persistent queue.
                    TODO: This will be changed to Optional when available.
                    See https://github.com/open-telemetry/opentelemetry-collector/issues/13822
                type: string
            wait_for_result:
                description: |-
                    WaitForResult determines if incoming requests are blocked until the request is processed or not.
                    Currently, this option is not available when persistent queue is configured using the storage configuration.
                type: boolean
        additionalProperties: false
    tls:
        description: TLS struct exposes TLS server configuration.
        type: object
        properties:
            ca_file:
                description: |-
                    Path to the CA cert. For a client this verifies the server certificate.
                    For a server this verifies client certificates. If empty uses system root CA.
                    (optional)
                type: string
            ca_pem:
                description: In memory PEM encoded cert. (optional)
                type: string
            cert_file:
                description: Path to the TLS cert to use for TLS required connections. (optional)
                type: string
            cert_pem:
                description: In memory PEM encoded TLS cert to use for TLS required connections. (optional)
                type: string
            cipher_suites:
                description: |-
                    CipherSuites is a list of TLS cipher suites that the TLS transport can use.
                    If left blank, a safe default list is used.
                    See https://go.dev/src/crypto/tls/cipher_suites.go for a list of supported cipher suites.
                type: array
                items:
                    type: string
            client_ca_file:
                description: |-
                    Path to the TLS cert to use by the server to verify a client certificate. (optional)
                    This sets the ClientCAs and ClientAuth to RequireAndVerifyClientCert in the TLSConfig. Please refer to
                    https://godoc.org/crypto/tls#Config for more information. (optional)
                type: string
            client_ca_file_reload:
                description: |-
                    Reload the ClientCAs file when it is modified
                    (optional, default false)
                type: boolean
            curve_preferences:
                description: |-
                    contains the elliptic curves that will be used in
                    an ECDHE handshake, in preference order
                    Defaults to empty list and "crypto/tls" defaults are used, internally.
                type: array
                items:
                    type: string
            include_system_ca_certs_pool:
                description: |-
                    If true, load system CA certificates pool in addition to the certificates
                    configured in this struct.
                type: boolean
            key_file:
                description: Path to the TLS key to use for TLS required connections. (optional)
                type: string
            key_pem:
                description: In memory PEM encoded TLS key to use for TLS required connections. (optional)
                type: string
            max_version:
                description: |-
                    MaxVersion sets the maximum TLS version that is acceptable.
                    If not set, refer to crypto/tls for defaults. (optional)
                type: string
            min_version:
                description: |-
                    MinVersion sets the minimum TLS version that is acceptable.
                    If not set, TLS 1.2 will be used. (optional)
                type: string
            reload_interval:
                description: |-
                    ReloadInterval specifies the duration after which the certificate will be reloaded
                    If not set, it will never be reloaded (optional)
                type: string
                pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
            tpm:
                description: Trusted platform module configuration
                type: object
                properties:
                    auth:
                        type: string
                    enabled:
                        type: boolean
                    owner_auth:
                        type: string
                    path:
                        description: |-
                            The path to the TPM device or Unix domain socket.
                            For instance /dev/tpm0 or /dev/tpmrm0.
                        type: string
                additionalProperties: false
        additionalProperties: false
    translation_strategy:
        description: |-
            TranslationStrategy controls how OTLP metric and attribute names are translated into Prometheus metric and label names.
            When set, this takes precedence over AddMetricSuffixes.
        type: string
    transport:
        description: |-
            Transport to use. Allowed protocols are "tcp", "tcp4" (IPv4-only), "tcp6" (IPv6-only), "udp", "udp4" (IPv4-only),
            "udp6" (IPv6-only), "ip", "ip4" (IPv4-only), "ip6" (IPv6-only), "unix", "unixgram", "unixpacket" and
            "npipe" (Windows named pipes, Windows-only).
        type: string
    without_scope_info:
        description: WithoutScopeInfo controls the addition of labels for the instrumentation scope.
        type: boolean
    write_timeout:
        description: |-
            WriteTimeout is the maximum duration before timing out
            writes of the response. It is reset whenever a new
            request's header is read. Like ReadTimeout, it does not
            let Handlers make decisions on a per-request basis.
            A zero or negative value means there will be no timeout.
        type: string
        pattern: ^(0|[-+]?((\d+(\.\d*)?|\.\d+)(ns|us|µs|μs|ms|s|m|h))+)$
additionalProperties: false
