// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/os-observability/redhat-opentelemetry-collector

go 1.25

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.58.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.58.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.58.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.58.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.58.0
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.152.0
	go.opentelemetry.io/collector/connector/forwardconnector v0.152.1
	go.opentelemetry.io/collector/extension/zpagesextension v0.152.1
	go.opentelemetry.io/collector/extension/memorylimiterextension v0.152.1
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/googleclientauthextension v0.152.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.152.1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/webhookeventreceiver v0.152.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.152.1
	go.opentelemetry.io/collector/exporter/otlpexporter v0.152.1
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.152.1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.152.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.152.1
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.152.1
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstarttimeprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.152.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.152.0
	go.opentelemetry.io/collector/service v0.152.1
	go.opentelemetry.io/collector/otelcol v0.152.1
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)





























































