name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install eBPF build dependencies
        run: sudo apt-get update && sudo apt-get install -y clang llvm

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: _build/go.mod

      - name: Verify
        run: make build

      - name: generate schemas
        run: make generate-schemas
